### PR TITLE
switch to nushell

### PR DESCRIPTION
**Pull request by Elsie19**
Closes #36.

### CODE REVIEW

**Review by oklopfer — CHANGES_REQUESTED** [review]
We can't be dropping translations. We will have to convert to a nushell compatible way. Their own website is funnily enough the perfect code to look at to know how nu i18n works (despite what you, elsie, found one admin on discord claiming): 
https://github.com/nushell/nushell.github.io/blob/main/i18n.nu
https://github.com/nushell/nushell.github.io/blob/main/i18n-meta.json
https://github.com/nushell/nushell.github.io/blob/main/README.md

**Comment by ajstrongdev** [comment]
I wholeheartedly agree, @Elsie19 we cannot be dropping translations for one of the most vital pieces of software on this distribution.

**Comment by ajstrongdev** [comment]
Does this also contain the descriptive modifier? @Elsie19

**Comment by Elsie19** [comment]
Superseded by #38.

**Pull request closed without merging**
